### ISSUE TITLE
How to use MM-Pred model on BPIC 2017 dataset

### ISSUE THREAD

**Issue by asfandyarazhar13** [StephenPauwels/edbn#3]
Hi, 

Just wanted to know how I can use your implementation of the MM-Pred model (Lin et al.) on the BPIC 2017 dataset found here: https://data.4tu.nl/articles/dataset/BPI_Challenge_2017/12696884 

I wonder if I have to use the role_discovery script? Not sure what that does, what does the role feature mean and how should I create it / format my data so that the model works? Please let me know as I am relatively new to this. Thanks!

Currently getting this error: 
```
PREPROCESSING: Converting Unnamed: 0
PREPROCESSING: Converting Action
PREPROCESSING: Converting org:resource
PREPROCESSING: Converting event
PREPROCESSING: Converting EventOrigin
PREPROCESSING: Converting EventID
PREPROCESSING: Converting lifecycle:transition
PREPROCESSING: Converting time:timestamp
PREPROCESSING: Converting case:LoanGoal
PREPROCESSING: Converting case:ApplicationType
PREPROCESSING: Converting case
PREPROCESSING: Converting Accepted
PREPROCESSING: Converting Selected
PREPROCESSING: Converting OfferID
Create k-context: 10
Train: 842015
Test: 360252
Start Vectorization
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'role_Prev9'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "<ipython-input-5-c6df8e4d46af>", line 204, in vect_map
    x_rl_inp.append(row["role_Prev%i" % i])
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'role_Prev9'
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
[<ipython-input-30-30e8e5ba969c>](https://localhost:8080/#) in <module>()
     34     train_log, test_log = logfile.splitTrainTest(70, split_case=False, method="train-test")
     35 
---> 36     model = train(train_log, epochs=100, early_stop=10)
     37 
     38     acc = test(test_log, model)

10 frames
[<ipython-input-30-30e8e5ba969c>](https://localhost:8080/#) in train(log, epochs, early_stop)
      1 def train(log, epochs=200, early_stop=42):
----> 2     return create_model(log, "tmp", epochs, early_stop)
      3 
      4 
      5 def update(model, log):

[<ipython-input-5-c6df8e4d46af>](https://localhost:8080/#) in create_model(log, output_folder, epochs, early_stop)
     72     from tensorflow.keras.optimizers import Nadam
     73 
---> 74     vec = vectorization(log)
     75     vocab_act_size = len(log.values["event"]) + 1
     76     vocab_role_size = len(log.values["role"]) + 1

[<ipython-input-5-c6df8e4d46af>](https://localhost:8080/#) in vectorization(log)
    173     part_vect_map = partial(vect_map, prefix_size=log.k)
    174     with mp.Pool(mp.cpu_count()) as p:
--> 175         result = np.array(p.map(part_vect_map, train_cases))
    176 
    177     vec['prefixes']['x_ac_inp'] = np.concatenate(result[:, 0])

[/usr/lib/python3.7/multiprocessing/pool.py](https://localhost:8080/#) in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

[/usr/lib/python3.7/multiprocessing/pool.py](https://localhost:8080/#) in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

[/usr/lib/python3.7/multiprocessing/pool.py](https://localhost:8080/#) in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

[/usr/lib/python3.7/multiprocessing/pool.py](https://localhost:8080/#) in mapstar()
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

[<ipython-input-5-c6df8e4d46af>](https://localhost:8080/#) in vect_map()
    202         for i in range(prefix_size - 1, 0, -1):
    203             x_ac_inp.append(row["event_Prev%i" % i])
--> 204             x_rl_inp.append(row["role_Prev%i" % i])
    205         x_ac_inp.append(row["event_Prev0"])
    206         x_rl_inp.append(row["role_Prev0"])

[/usr/local/lib/python3.7/dist-packages/pandas/core/series.py](https://localhost:8080/#) in __getitem__()
    940 
    941         elif key_is_scalar:
--> 942             return self._get_value(key)
    943 
    944         if is_hashable(key):

[/usr/local/lib/python3.7/dist-packages/pandas/core/series.py](https://localhost:8080/#) in _get_value()
   1049 
   1050         # Similar to Index.get_value, but we do not fall back to positional
-> 1051         loc = self.index.get_loc(label)
   1052         return self.index._get_values_for_loc(self, loc, label)
   1053 

[/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc()
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'role_Prev9'
```

**Comment by asfandyarazhar13** [comment]
Even when I try with the BPIC12W.csv file you have here in the repo, I get the following traceback:

```
PREPROCESSING: Converting case
PREPROCESSING: Converting event
PREPROCESSING: Converting startTime
PREPROCESSING: Converting completeTime
PREPROCESSING: Converting creator
PREPROCESSING: Converting variant
PREPROCESSING: Converting variant-index
PREPROCESSING: Converting (case)_AMOUNT_REQ
Create k-context: 10
Train: 44272
Test: 17177
Start Vectorization
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:175: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-31-394092e0f62c>](https://localhost:8080/#) in <module>()
     35     train_log, test_log = logfile.splitTrainTest(70, split_case=False, method="train-test")
     36 
---> 37     model = train(train_log, epochs=100, early_stop=10)
     38 
     39     acc = test(test_log, model)

2 frames
[<ipython-input-31-394092e0f62c>](https://localhost:8080/#) in train(log, epochs, early_stop)
      1 def train(log, epochs=200, early_stop=42):
----> 2     return create_model(log, "tmp", epochs, early_stop)
      3 
      4 
      5 def update(model, log):

[<ipython-input-5-c6df8e4d46af>](https://localhost:8080/#) in create_model(log, output_folder, epochs, early_stop)
     72     from tensorflow.keras.optimizers import Nadam
     73 
---> 74     vec = vectorization(log)
     75     vocab_act_size = len(log.values["event"]) + 1
     76     vocab_role_size = len(log.values["role"]) + 1

[<ipython-input-5-c6df8e4d46af>](https://localhost:8080/#) in vectorization(log)
    181 
    182     vec['next_evt']['y_ac_inp'] = to_categorical(vec['next_evt']['y_ac_inp'], num_classes=len(log.values["event"])+1)
--> 183     vec['next_evt']['y_rl_inp'] = to_categorical(vec['next_evt']['y_rl_inp'], num_classes=len(log.values["role"])+1)
    184     return vec
    185 

KeyError: 'role'
```
